---
- hosts: all
  become: yes
  roles:
    - common

- hosts: nfs
  become: yes
  roles:
    - nfs

- hosts: web
  become: yes
  roles:
    - web

- hosts: lb
  become: yes
  roles:
    - loadbalancer