---
- name: install nfs related stuff
  yum: name={{ item }}
  with_items:
    - nfs-utils

- name: create nfs directory & set mode
  file: path=/var/nfsshare state=directory mode=0777

- name: enable need services for nfs
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server
    - nfs-idmap

- name: add nfs export file
  template: src=exports.j2 dest=/etc/exports

- name: start nfs
  service: name=nfs-server state=restarted enabled=yes


