---
- name: install web related stuff
  yum: name={{ item }}
  with_items:
    - httpd
    - mysql
    - php
    - php-cli
    - php-mysql

- name: install nfs
  yum: name=nfs-utils

- name: create nfs mount dir
  file: path=/mnt/nfs/nfsshare state=directory recurse=yes

- name: mount nfs at boot
  lineinfile: dest=/etc/fstab line="10.2.0.60:/var/nfsshare    /mnt/nfs/nfsshare   nfs defaults 0 0"

- name: enable nfs service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server
    - nfs-idmap

- name: change httpd DocumentRoot
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="DocumentRoot "/var/www/html"" line="DocumentRoot "/mnt/nfs/nfsshare""

- name: change httpd Directory
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="<Directory "/var/www/html">" line="<Directory "/mnt/nfs/nfsshare">"


- name: enable & start httpd
  service: name=httpd enabled=yes state=started

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=120
  become: false