---
- name: Install EPEL repo
  yum: name={{ item }}
  with_items:
    - epel-release

- name: Install common packages
  yum: name={{ item }}
  with_items:
    - yum-utils
    - nano
    - wget
    - libselinux-python
    - epel-release
    - unzip
    - htop
    - python-httplib2
    - perl

- name: Disable firewall
  service: name=firewalld state=stopped enabled=no

- name: Add SSH keys
  authorized_key: user=root key="{{ item }}"
  with_items:
    - "{{ lookup('file', '/home/goran/.ssh/id_rsa.pub') }}"

- name: Disable SELinux
  selinux: state=disabled

- name: Update all packages
  yum: name=* state=latest

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=120
  become: false