# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vbguest.auto_update = false
    config.ssh.insert_key = false

   config.vm.define "nfs" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.network :private_network, ip: "10.2.0.60",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "nfs.dt"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.cpus = 1
    end
  end

  config.vm.define "mysql" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.network :private_network, ip: "10.2.0.50",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "mysql.dt"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.cpus = 4
    end
  end

  config.vm.define "apache-1" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.network :private_network, ip: "10.2.0.41",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "apache-1.dt"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.cpus = 1
    end
  end

  config.vm.define "apache-2" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.network :private_network, ip: "10.2.0.42",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "apache-2.dt"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.cpus = 1
    end
  end

  config.vm.define "loadbalancer" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.network :private_network, ip: "192.168.200.10"
    machine.vm.network :private_network, ip: "10.2.0.40",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "loadbalancer.dt"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.cpus = 2
    end
  end

end
